language: php

php:
  - 5.4
  - 5.5
  - 5.6
  
cache: 
  - apt

env:
  - PHALCON_VERSION="2.0.0"

before_script:
  - ./tests/install-php-extension.sh ${PHALCON_VERSION}
  - php -r 'echo \Phalcon\Version::get()."\n";'

install:
 - composer --prefer-dist install

script:
 - vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 application/ library/ public/
